# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/first_database
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate 6 compatibility fix
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# OpenAPI/Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Security (???????? ??? ??????????)
spring.security.user.name=admin
spring.security.user.password=admin

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

### Security ###
jwt.expiration=5
jwt.secret=d7e0ff8c3b8fcacb5c4e3ea330b962e25f14096520995778cf7a18f61188f156714d9622006b1b42c13602f44760356992cb8fa5f4862cc8c5f3eef639ee78bb